name: TrustWalletCore
options:
  bundleIdPrefix: com.trustwallet
  createIntermediateGroups: true
settings:
  base:
    BUILD_LIBRARY_FOR_DISTRIBUTION: true
    CLANG_CXX_LANGUAGE_STANDARD: c++17
    CODE_SIGN_STYLE: Manual
    ENABLE_BITCODE: false
    SUPPORTS_MACCATALYST: false
    SWIFT_VERSION: 5.0
  configs:
    release:
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -Owholemodule
targets:
  WalletCore:
    dependencies:
    - framework: Carthage/Build/SwiftProtobuf.xcframework
    - framework: wallet-core/WalletCoreCommon.xcframework
    - sdk: libc++.tbd
    deploymentTarget:
      iOS: '12.0'
    platform:
    - iOS
    settings:
      CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION: YES_ERROR
      SKIP_INSTALL: false
    sources:
    - wallet-core/Sources
    - wallet-core/include
    type: framework
