#!/bin/bash

if [ -z $1 ]; then
    echo "Usage: ./update 0.12.25"
    exit 0
fi
VERSION=$1
BUILD_NAME="TrustWalletCore-iOS-$VERSION.zip"
BUILD_URL="https://github.com/trustwallet/wallet-core/releases/download/$VERSION/$BUILD_NAME"
# BUILD_URL="http://127.0.0.1:8000/$BUILD_NAME"
UNZIP_DIR=wallet-core

rm -rf $UNZIP_DIR $BUILD_NAME

echo "Downloading $BUILD_URL"
curl -L $BUILD_URL -o $BUILD_NAME
unzip $BUILD_NAME -d $UNZIP_DIR

echo "Building..."
xcodegen && xcodebuild
